#!/usr/bin/env bash

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
  if [[ $(pidof "${_prs}") ]]; then
    killall -9 "${_prs}"
  fi
done

# Polkit agent
if [[ ! $(pidof xfce-polkit) ]]; then
  /usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch notification daemon (mako)
~/.config/sway/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/sway/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &

# Eyes saver
#wlsunset -l 50.3590 -L 3.52506 &

# Start mpd
exec mpd &
