#!/usr/bin/env bash

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MAIN_MONITOR="DP-1"
EXTERNAL_SECOND_MONITOR="HDMI-A-1"

if [[ $(xrandr -q | grep -e "^${EXTERNAL_MAIN_MONITOR} connected" -e "^${EXTERNAL_SECOND_MONITOR} connected") ]]; then
	CONFIG="$HOME/.config/sway/waybar/config_multiple"
else
	CONFIG="$HOME/.config/sway/waybar/config"
fi

STYLE="$HOME/.config/sway/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi
