#!/usr/bin/env bash

xrandr --output DisplayPort-0 --mode 2560x1440 --rate 60 --rotate normal --pos 0x0 --primary
xrandr --output eDP --mode 1920x1080 --rate 60 --rotate normal --pos 640x1441
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate left --pos 2560x0
#xrandr --output eDP --off

# xrandr --output HDMI-A-0 --mode 1920x1080 --rate 60 --rotate normal --pos 0x0 --primary
# xrandr --output DisplayPort-0 --mode 1920x1080 --rate 60 --rotate normal --pos 2560x1080
# xrandr --output eDP --mode 1920x1080 --rate 60  --rotate normal --pos 640x1080